ORIGINAL_LENGTH = 2.84
ORIGINAL_WIDHT = 1.42

TABLE_WIDTH = 41.64
TABLE_LENGTH = 83.28

RELATION_ORIGNAL_USED = ORIGINAL_LENGTH/TABLE_LENGTH

TABLE_HEIGHT = 3
MARGIN_WIDTH = 4
LEGS_HEIGHT = 18
LEGS_SIZE = 4
MARGIN_LEG_TABLE = TABLE_WIDTH/6
TABLE_PROF = (
    TABLE_HEIGHT / 2
)  # Aixo es la profunditat de la moqueta a l'interor de la taula
# Per a tenir la moqueta de la taula a 0,0,0 aquestes son les coordenades de la taula => (-MARGIN_WIDTH, -TABLE_PROF, -MARGIN_WIDTH)
TABLE_POSITION = (-MARGIN_WIDTH, -TABLE_PROF, -MARGIN_WIDTH)
LEG_1 = (TABLE_POSITION[0] + MARGIN_LEG_TABLE, TABLE_POSITION[1], TABLE_POSITION[2] + MARGIN_LEG_TABLE)
LEG_2 = (
    TABLE_POSITION[0] + TABLE_WIDTH + MARGIN_WIDTH - MARGIN_LEG_TABLE,
    TABLE_POSITION[1],
    TABLE_POSITION[2] + MARGIN_LEG_TABLE,
)
LEG_3 = (
    TABLE_POSITION[0] + TABLE_WIDTH + MARGIN_WIDTH - MARGIN_LEG_TABLE,
    TABLE_POSITION[1],
    TABLE_POSITION[2] + TABLE_LENGTH + MARGIN_WIDTH - MARGIN_LEG_TABLE,
)
LEG_4 = (
    TABLE_POSITION[0] + MARGIN_LEG_TABLE,
    TABLE_POSITION[1],
    TABLE_POSITION[2] + TABLE_LENGTH + MARGIN_WIDTH - MARGIN_LEG_TABLE,
)
TABLE_FLOOR = (
    TABLE_POSITION[0] + MARGIN_WIDTH,
    TABLE_POSITION[1] + TABLE_PROF,
    TABLE_POSITION[2] + +MARGIN_WIDTH,
)

### BALLS
SLICES = 100
STACKS = 100
RADIUS = 1
BALL_COLOR = (1, 0, 1)

# SubDivision ball colour
SDCOLOR1 = (1, 0, 0)
SDCOLOR2 = (1, 1, 0)
SDDEPTH = 4

# Light
# LIGHT_POSITION = (TABLE_WIDTH//2 + MARGIN_WIDTH, 30, TABLE_LENGTH//2 + MARGIN_WIDTH)
LIGHT_POSITION = (0, 5, 0)

FIRST_BALLS_POSITION = [(TABLE_WIDTH/5, 1, TABLE_LENGTH/10), (TABLE_WIDTH - TABLE_WIDTH/5, 1, TABLE_LENGTH/10)]

#Terra
T_X = 225
T_Z = 225
#Sostre
S_HEIGHT = 80
S_X = 225
S_Z = 225
#Parets
P_X = 225
P_Z = 225
P_H = 80
P_F1 = 225/3
P_F2 = 550/3
P_F3 = 50/3
P_F4 = 100/3


# Line
LINE_POSITION = (TABLE_WIDTH/5, 1, TABLE_LENGTH/10)
 